language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-configurator-component' ]; then cd .. && eval "mv $currentfolder generator-configurator-component" && cd generator-configurator-component; fi

